[tool.poetry]
name = "spectral_synthesizer"
version = "0.1.2"
description = "Generate synthetic spectra with injected RVs"
authors = ["Kamuish <andremiguel952@gmail.com>"]
packages = [
    { include = "spectral_synthesizer" },
]

[tool.poetry.dependencies]
python = "^3.8"
numpy = "^1.22.3"
tabletexifier = "^0.1.9"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
