[tool.poetry]
name = "pyperclip-cli"
version = "0.1.2"
description = "Pyperclip CLI - cross-platform clipboard utility"
authors = ["Xinyuan Chen <45612704+tddschn@users.noreply.github.com>"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/tddschn/pyperclip-cli"
repository = "https://github.com/tddschn/pyperclip-cli"
classifiers = [
	"Topic :: Utilities"
]
keywords = ["clipboard", "clipboard-cli", "cli", "pyperclip"]
[tool.poetry.scripts]
pyperclip = "pyperclip_cli.cli:main"

[tool.poetry.urls]
"Bug Tracker" = "https://github.com/tddschn/pyperclip-cli/issues"

[tool.poetry.dependencies]
python = "^3.10"
pyperclip = "^1.8.2"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
toml = "^0.10.2"
yapf = "^0.32.0"
better-exceptions = "^0.3.3"
bump2version = "^1.0.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
