[tool.poetry]
name = "xlsxq"
version = "0.1.2"
description = "xlsxq is a lightweight and flexible command-line .xlsx processor."
authors = ["kumarstack55 <kumarstack55@gmail.com>"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/kumarstack55/xlsxq"
repository = "https://github.com/kumarstack55/xlsxq"
documentation = "https://github.com/kumarstack55/xlsxq"
classifiers =  [
    "Development Status :: 4 - Beta",
    "Topic :: Office/Business :: Financial :: Spreadsheet"
]

[tool.poetry.scripts]
xlsxq = "xlsxq:main"

[tool.poetry.dependencies]
python = "^3.9"
openpyxl = "^3.0.9"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
