[tool.poetry]
name = "prettyplot"
version = "0.0.1alpha0"
description = "Python package for astonishing and bold plots"
authors = ["Cristiano Moraes Bilacchi <cristiano.bilacchi@icloud.com>"]

[tool.poetry.dependencies]
python = "^3.7"
scikit-learn = "^1.0.2"
matplotlib = "^3.2"

[tool.poetry.dev-dependencies]
pytest = "^7.1.2"
blue = "^0.8.0"
isort = "^5.10.1"
prospector = "^1.7.7"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"