[tool.poetry]
name = "weatherchart"
version = "1.0.5"
description = "Generate chart image based on 7 day forecast form a given location"
authors = ["pub12 <pubudu79@gmail.com>"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/pubs12/weatherchart"

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
