[tool.poetry]
name = "linkhub_prometheus_exporter"
# Version is dynamically managed by `poetry-dynamic-versioning` plugin.
version = "0.1.4"
description = "A Prometheus metrics exporter for Alcatel Linkhub 4G router boxes"
authors = ["Gergely Imreh <gergely@imreh.net>"]
homepage = "https://github.com/imrehg/linkhub_prometheus_exporter"
repository = "https://github.com/imrehg/linkhub_prometheus_exporter"
readme = "README.md"
license = "Apache-2.0"
include = [
    "LICENSE.txt",
]

[tool.poetry.dependencies]
python = "^3.9"
prometheus-client = "^0.14.1"
requests = "^2.27.1"
dynaconf = "^3.1.8"
types-requests = "^2.27.25"

[tool.poetry.dev-dependencies]
pytest = "*"
pytest-cov = "*"
requests-mock = "*"
isort = "*"
black = "*"
flake8 = "*"
mypy = "*"
bandit = "*"

[tool.isort]
profile = "black"
src_paths = ["src", "tests"]

[tool.black]
line-length = 79

[[tool.mypy.overrides]]
module = [
    "dynaconf",  # Should be necessary while this is open: https://github.com/rochacbruno/dynaconf/issues/448
]
ignore_missing_imports = true

[tool.poetry.scripts]
linkhub_exporter = "linkhub_prometheus_exporter.exporter:main"

[tool.poetry-dynamic-versioning]
enable = true
vcs = "git"
style = "pep440"

[tool.poetry-dynamic-versioning.substitution]
files = ["*/__init__.py", "*/*/__init__.py"]

[build-system]
requires = ["poetry>=1.2.0b1", "poetry-dynamic-versioning-plugin"]
build-backend = "poetry.masonry.api"
