[tool.poetry]
name = "nexus_integra_api"
packages = [
    {include = "nexus_api"}
]
version = "0.6.1"
authors = ["Nexus Integra"]
description =" Nexus API connection methods and utilities"
readme = "README.md"
homepage = "https://nexusintegra.io"

[tool.poetry.dependencies]
python = "^3.10"
pandas = "*"

[tool.poetry.dev-dependencies]
python-dotenv = "*"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
