[tool.poetry]
name = "roux-algo-geneweaver-kargers"
version = "0.0.2"
description = "An implementation of Krager's Algorithm to find similar Genesets"
authors = ["Alex Berger <berger.ale@northeastern.edu>"]
license = "Apache 2"
readme = "README.md"
packages = [{include = "roux/algo/geneweaver/kargers", from = 'src'}]

[tool.poetry.dependencies]
python = "^3.9"
SQLAlchemy = "^1.4.35"
pydantic = {extras = ["dotenv"], version = "^1.9.0"}
psycopg2-binary = "^2.9.3"
networkx = "^2.8"
matplotlib = "^3.5.1"
numpy = "^1.22.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
